const bibleData = [
    // Old Testament (구약)
    { ko: "창세기", en: "Genesis", chapters: 50 },
    { ko: "출애굽기", en: "Exodus", chapters: 40 },
    { ko: "레위기", en: "Leviticus", chapters: 27 },
    { ko: "민수기", en: "Numbers", chapters: 36 },
    { ko: "신명기", en: "Deuteronomy", chapters: 34 },
    { ko: "여호수아", en: "Joshua", chapters: 24 },
    { ko: "사사기", en: "Judges", chapters: 21 },
    { ko: "룻기", en: "Ruth", chapters: 4 },
    { ko: "사무엘상", en: "1 Samuel", chapters: 31 },
    { ko: "사무엘하", en: "2 Samuel", chapters: 24 },
    { ko: "열왕기상", en: "1 Kings", chapters: 22 },
    { ko: "열왕기하", en: "2 Kings", chapters: 25 },
    { ko: "역대상", en: "1 Chronicles", chapters: 29 },
    { ko: "역대하", en: "2 Chronicles", chapters: 36 },
    { ko: "에스라", en: "Ezra", chapters: 10 },
    { ko: "느헤미야", en: "Nehemiah", chapters: 13 },
    { ko: "에스더", en: "Esther", chapters: 10 },
    { ko: "욥기", en: "Job", chapters: 42 },
    { ko: "시편", en: "Psalms", chapters: 150 },
    { ko: "잠언", en: "Proverbs", chapters: 31 },
    { ko: "전도서", en: "Ecclesiastes", chapters: 12 },
    { ko: "아가", en: "Song of Solomon", chapters: 8 },
    { ko: "이사야", en: "Isaiah", chapters: 66 },
    { ko: "예레미야", en: "Jeremiah", chapters: 52 },
    { ko: "예레미야애가", en: "Lamentations", chapters: 5 },
    { ko: "에스겔", en: "Ezekiel", chapters: 48 },
    { ko: "다니엘", en: "Daniel", chapters: 12 },
    { ko: "호세아", en: "Hosea", chapters: 14 },
    { ko: "요엘", en: "Joel", chapters: 3 },
    { ko: "아모스", en: "Amos", chapters: 9 },
    { ko: "오바댜", en: "Obadiah", chapters: 1 },
    { ko: "요나", en: "Jonah", chapters: 4 },
    { ko: "미가", en: "Micah", chapters: 7 },
    { ko: "나훔", en: "Nahum", chapters: 3 },
    { ko: "하박국", en: "Habakkuk", chapters: 3 },
    { ko: "스바냐", en: "Zephaniah", chapters: 3 },
    { ko: "학개", en: "Haggai", chapters: 2 },
    { ko: "스가랴", en: "Zechariah", chapters: 14 },
    { ko: "말라기", en: "Malachi", chapters: 4 },
    // New Testament (신약)
    { ko: "마태복음", en: "Matthew", chapters: 28 },
    { ko: "마가복음", en: "Mark", chapters: 16 },
    { ko: "누가복음", en: "Luke", chapters: 24 },
    { ko: "요한복음", en: "John", chapters: 21 },
    { ko: "사도행전", en: "Acts", chapters: 28 },
    { ko: "로마서", en: "Romans", chapters: 16 },
    { ko: "고린도전서", en: "1 Corinthians", chapters: 16 },
    { ko: "고린도후서", en: "2 Corinthians", chapters: 13 },
    { ko: "갈라디아서", en: "Galatians", chapters: 6 },
    { ko: "에베소서", en: "Ephesians", chapters: 6 },
    { ko: "빌립보서", en: "Philippians", chapters: 4 },
    { ko: "골로새서", en: "Colossians", chapters: 4 },
    { ko: "데살로니가전서", en: "1 Thessalonians", chapters: 5 },
    { ko: "데살로니가후서", en: "2 Thessalonians", chapters: 3 },
    { ko: "디모데전서", en: "1 Timothy", chapters: 6 },
    { ko: "디모데후서", en: "2 Timothy", chapters: 4 },
    { ko: "디도서", en: "Titus", chapters: 3 },
    { ko: "빌레몬서", en: "Philemon", chapters: 1 },
    { ko: "히브리서", en: "Hebrews", chapters: 13 },
    { ko: "야고보서", en: "James", chapters: 5 },
    { ko: "베드로전서", en: "1 Peter", chapters: 5 },
    { ko: "베드로후서", en: "2 Peter", chapters: 3 },
    { ko: "요한일서", en: "1 John", chapters: 5 },
    { ko: "요한이서", en: "2 John", chapters: 1 },
    { ko: "요한삼서", en: "3 John", chapters: 1 },
    { ko: "유다서", en: "Jude", chapters: 1 },
    { ko: "요한계시록", en: "Revelation", chapters: 22 }
];

// Helper to get total chapters
const TOTAL_CHAPTERS = bibleData.reduce((acc, book) => acc + book.chapters, 0);
console.log(`Total Chapters: ${TOTAL_CHAPTERS}`); // Should be 1189
